apiVersion: v1
kind: ServiceAccount
metadata:
  name: logging
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: logging
  namespace: kube-system
rules:
  - apiGroups:
      - ''
    resources:
      - 'pods'
    verbs:
      - 'create'
      - 'delete'
      - 'get'
      - 'list'
      - 'patch'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: logging
  namespace: nfv
subjects:
  - kind: ServiceAccount
    name: logging
    namespace: kube-system
roleRef:
  kind: Role
  name: logging
  apiGroup: rbac.authorization.k8s.io