---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: logging
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: logging-role
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apps"]
    resources: ["slacks","slacktasks","sinks","filters"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: logging-rolebinding
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: logging
    namespace: kube-system
roleRef:
  kind: Role
  name: logging-role
  apiGroup: rbac.authorization.k8s.io